// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "approov_service_flutter_httpclient",
    platforms: [
        .iOS("11.0")
    ],
    products: [
        .library(name: "approov-service-flutter-httpclient", targets: ["approov_service_flutter_httpclient"])
    ],
    dependencies: [
        .package(url: "https://github.com/approov/approov-ios-sdk.git", from: "3.5.3"),
        // Generated by the `flutter` tool at build time; provides Flutter/Flutter.h.
        .package(name: "FlutterFramework", path: "../FlutterFramework")
    ],
    targets: [
        .target(
            name: "approov_service_flutter_httpclient",
            dependencies: [
                .product(name: "Approov", package: "approov-ios-sdk"),
                .product(name: "FlutterFramework", package: "FlutterFramework")
            ],
            cSettings: [
                .headerSearchPath("include/approov_service_flutter_httpclient")
            ]
        )
    ]
)
